version: 2

project_name: ocpm

before:
  hooks:
    - go mod tidy

builds:
  - id: ocpm
    main: ./cmd/ocpm
    binary: ocpm
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.buildVersion={{.Version}} -X main.commit={{.FullCommit}} -X main.date={{.Date}}

archives:
  - id: ocpm
    ids:
      - ocpm
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github-native
